name: THM Badge Auto Update

on:
  schedule:
    - cron: "0 */6 * * *"   # rulează la fiecare 6 ore
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download latest THM badge
        run: |
          mkdir -p assets
          curl -sL "https://tryhackme-badges.s3.amazonaws.com/vladvontranssilvanien.png" -o assets/thm_badge.png

      - name: Commit if changed
        run: |
          if git diff --quiet assets/thm_badge.png; then
            echo "No changes"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/thm_badge.png
          git commit -m "chore: refresh THM badge"
          git push

